Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"

	# Required for NFS to work, pick any local IP
	config.vm.network :private_network, ip: '192.168.50.50'

	# Use NFS for shared folders for better performance
	config.vm.synced_folder '.', '/vagrant',
		type:"nfs",
    	mount_options: %w{rw,async,fsc,nolock,vers=3,udp,rsize=32768,wsize=32768,hard,noatime,actimeo=2}

    config.vm.synced_folder 'C:\Users\nick\.ssh', '/tmp/.ssh'

	config.vm.provider "virtualbox" do |v|
    	v.name = "Labkey Vagrant"
    	v.memory = 16384
  		v.cpus = 6
  		v.default_nic_type = "Am79C970A"
  		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
	end

	config.vm.provision "shell" do |s|
    	s.path = "provision/build_labkey.sh"
	end

end

