version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: labkey-mssql-server
    user: root
    volumes:
      - labkey_volume:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Labkey1098!
    ports:
      - "1433:1433"

volumes:
  labkey_volume:
    driver: local
    name: labkey-volume
